export const SERVICES = [
  {
    id: '1',
    title: 'ITR Filing',
    description: 'File your Income Tax Returns accurately and on time with expert CA assistance.',
    price: 999,
    category: 'Accounting Services',
    icon: '📋',
    duration: '2-3 days',
    popular: true,
    fullDescription: 'Our expert CAs handle your Income Tax Return filing end-to-end. We ensure maximum deductions, error-free filing, and timely submission to avoid penalties.',
    documents: [
      'PAN Card',
      'Aadhaar Card',
      'Form 16 (if salaried)',
      'Bank Statements (last 12 months)',
      'Investment proofs (80C, 80D, etc.)',
      'Previous year ITR (if applicable)',
    ],
  },
  {
    id: '2',
    title: 'GST Registration',
    description: 'Register for GST and stay compliant with all GST regulations effortlessly.',
    price: 1499,
    category: 'Business Services',
    icon: '🧾',
    duration: '3-5 days',
    popular: true,
    fullDescription: 'Get your GSTIN quickly with our streamlined GST registration process. We handle all documentation, application filing, and follow-up with the tax authorities.',
    documents: [
      'PAN Card of business/owner',
      'Aadhaar Card of owner',
      'Business address proof',
      'Bank account details',
      'Digital signature (if company)',
      'MOA/AOA (if company)',
    ],
  },
  {
    id: '3',
    title: 'Company Registration',
    description: 'Register your Private Limited, LLP, or One Person Company with ease.',
    price: 6999,
    category: 'Company Incorporation',
    icon: '🏢',
    duration: '7-10 days',
    popular: false,
    fullDescription: 'Start your business the right way. We handle complete company incorporation including name approval, DIN, DSC, MOA/AOA drafting, and Certificate of Incorporation.',
    documents: [
      'PAN Card of all directors',
      'Aadhaar Card of all directors',
      'Passport-size photographs',
      'Address proof of registered office',
      'NOC from property owner',
      'Utility bill (not older than 2 months)',
    ],
  },
  {
    id: '4',
    title: 'Tax Audit',
    description: 'Comprehensive tax audit services for businesses and professionals.',
    price: 4999,
    category: 'Compliance Services',
    icon: '🔍',
    duration: '5-7 days',
    popular: false,
    fullDescription: 'Our experienced CAs conduct thorough tax audits as required under Section 44AB of the Income Tax Act, ensuring compliance and minimizing audit risk.',
    documents: [
      'Audited financial statements',
      'Trial balance',
      'Bank statements',
      'TDS certificates',
      'Loan statements',
      'Previous audit report',
    ],
  },
  {
    id: '5',
    title: 'GST Return Filing',
    description: 'Monthly, quarterly, and annual GST return filing with reconciliation.',
    price: 799,
    category: 'Business Services',
    icon: '📊',
    duration: '1-2 days',
    popular: true,
    fullDescription: 'Never miss a GST return deadline. We file GSTR-1, GSTR-3B, GSTR-9, and reconcile your input tax credit to maximize savings and avoid penalties.',
    documents: [
      'Sales invoices',
      'Purchase invoices',
      'Credit/debit notes',
      'E-way bills (if applicable)',
      'Previous GSTR filings',
    ],
  },
  {
    id: '6',
    title: 'Payroll Management',
    description: 'Complete payroll processing with PF, ESI, and TDS compliance.',
    price: 2499,
    category: 'Compliance Services',
    icon: '💰',
    duration: 'Monthly',
    popular: false,
    fullDescription: 'Outsource your payroll to us and ensure accurate salary processing, statutory compliance for PF/ESI/PT, Form 16 generation, and TDS filings.',
    documents: [
      'Employee list with salary details',
      'PAN of all employees',
      'Bank account details',
      'Previous payroll records',
      'Offer letters',
    ],
  },
];

export const MOCK_REQUESTS = [
  { id: 'REQ001', service: 'ITR Filing', status: 'completed', date: '2024-12-01', amount: 999 },
  { id: 'REQ002', service: 'GST Registration', status: 'inprogress', date: '2025-01-10', amount: 1499 },
  { id: 'REQ003', service: 'Tax Audit', status: 'pending', date: '2025-01-20', amount: 4999 },
];

export const ADMIN_REQUESTS = [
  { id: 'REQ001', user: 'Rahul Sharma', service: 'ITR Filing', status: 'completed', date: '2024-12-01', amount: 999 },
  { id: 'REQ002', user: 'Priya Mehta', service: 'GST Registration', status: 'inprogress', date: '2025-01-10', amount: 1499 },
  { id: 'REQ003', user: 'Amit Verma', service: 'Tax Audit', status: 'pending', date: '2025-01-20', amount: 4999 },
  { id: 'REQ004', user: 'Sunita Rao', service: 'Company Registration', status: 'pending', date: '2025-01-22', amount: 6999 },
  { id: 'REQ005', user: 'Vikram Singh', service: 'GST Return Filing', status: 'completed', date: '2025-01-05', amount: 799 },
];
